### PR TITLE
Some bootstrap styles have an extra pagination class based on the list t...

### PR DESCRIPTION
**Pull request by Geolim4**
Some bootstrap styles have an extra pagination class based on the list tag ( <_ul> ).

### CODE REVIEW

**Comment by flaviusmatis** [comment]
That could be useful I guess, but the default listStyle should be empty.

**Comment by Geolim4** [comment]
Does it mean i need to add additional fix ?

**Comment by flaviusmatis** [comment]
No, I just merged the fix and then changed the default for listStyle.

**Comment by Geolim4** [comment]
Great :)

**Pull request merged**
