### PR TITLE
Add non-anchor mode

### PR DESCRIPTION
**Pull request by AlexEndris**
Essentially, I didn't want an anchor to do anything to the URL. So if the useAnchors option is false it will use a span instead.

### CODE REVIEW

**Comment by salzersoftware** [comment]
Thanks for making this PR @AlexEndris. I was looking to do the exact same thing! I didn't like the paging links trashing the browser history.

**Comment by AlexEndris** [comment]
@salzersoftware I guess both scenarios have their right to exist. That's why I was so keen on having this as an option. Too bad it's not merged into master, though. Should there be anything buggy with this, please do come back and tell me!

**Comment by bhamdan** [comment]
We are needing this well. We modified ours to just always prevent the URL updates at the moment.

**Comment by jross-imsteris** [comment]
Please pull this to master. It's a very useful addition.

**Comment by roninbv** [comment]
**FOR THE LOVE OF GOD PLEASE MERGE THIS TO MASTER.**

**Comment by bhamdan** [comment]
yay!

**Comment by roninbv** [comment]
thanks @flaviusmatis! we definitely needed this ability.

**Pull request merged**
