### PR TITLE
disable prev/next if it is on first/last page

### PR DESCRIPTION
**Pull request by aguegu**
disable prev/next button if it is already on first/last page. 

Just a one line tweaking. 

as discussed in issue #103

### CODE REVIEW

**Comment by timgws** [comment]
@aguegu I noticed you just +1'd the version, could you please also tag that commit?

The version should be tagged when the composer.json file is updated.

Just run:

    git tab v0.0.2
    git push --tag

**Comment by aguegu** [comment]
I can only tag on my fork. And it is already done. That is why you can see it. I am afraid that I can tag on this origin repo.

**Comment by aguegu** [comment]
I can only tag on my fork. And it is already done. That is why you can see it. I am afraid that I can tag on this origin repo.

**Comment by timgws** [comment]
noted, apologies @aguegu...

**Pull request merged**
