### PR TITLE
Update hash value in the draw method

### PR DESCRIPTION
**Pull request by bux**
If you've clicked on a pager link a hash is being appended to the url. If you then programatically change the page via 

```
pager.pagination("updateItems", totalPages * pageSize);
pager.pagination("drawPage", currentPage);
```

the hash doesn't get updated. This PR fixes this.

### CODE REVIEW

**Comment by timgws** [comment]
:+1: thanks for this!

**Comment by timgws** [comment]
:+1: thanks for this! Is there a chance that you could also add a test inside `tests/spec/SimplePaginationSpec.js` to ensure that there will not be any regressions/further bugs to this functionality?

**Comment by bux578** [comment]
Yeah, sure. Will do.

**Comment by bux578** [comment]
I don't know how to properly test this.

**Pull request closed without merging**
